import '~/styles/globals.css';

import { type Metadata } from 'next';

import { Button } from '../_components/ui/Button';

export const metadata: Metadata = {
    title: 'Sign in',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default async function UserFlowLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <>
            <nav className="flex items-center mx-44 my-12 justify-between">
                <h1 className="font-medium bg-gradient-to-t px-4 rounded-full py-1 from-blue-500 to-zinc-800  flex items-center gap-2">
                    Surf trackz
                </h1>
                <div>
                    <Button>Sign Up</Button>
                </div>
            </nav>

            <div className="flex items-center justify-center grow">{children}</div>
        </>
    );
}
